### ISSUE TITLE
리눅스 환경에서 스프링 부트 분리된 프로파일 실행 문제

### ISSUE THREAD

**Issue by fp024** [fp024/spring-boot-reactive-study#2]
## 문제

https://github.com/fp024/spring-boot-reactive-study/issues/1 문제로 어쩌다보니 만든 linux 프로필을 윈도우환경에서 테스트 할 때는 프로필 전환이 잘되는 것을 확인했는데.. 이상하게 Ubuntu 나 Rocky리눅스에서는 잘 안된다...

* application.yml

  ```yml
  # MongoDB의 신버전은 다운로드가 막히거나 URL 패턴이 바뀐 것 같다. (응답이 403으로 뜸)
  # http://downloads.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ssl-4.0.12.zip
  # https://www.mongodb.org/dl/win32/x86_64 링크목록을 보았을 때, 받을 수 있는 가장 최후 버전이 4.0.12 같음
  # https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/master/src/main/java/de/flapdoodle/embed/mongo/distribution/Version.java
  
  # Verson.java 파일을 확인해보았을 때, 5.0.6 버전 열거 타입이 선언되어있어 적용해보니 잘된다.
  # 이 클래스 파일을 확인해가며 버전을 올리면 되겠다.
  spring:
    mongodb:
      embedded:
        version: 5.0.6
    webflux:
      hiddenmethod:
        filter:
          enabled: true
  
  # MongoDB 관련 로그가 기본이 INFO라서 다른 로그 찾기가 힘들어, root를 WARN으로 올림.
  logging:
    level:
      root: WARN
      "[org.springframework.data]": INFO
      "[org.fp024]": INFO
  
  ---
  spring:
    config:
      activate:
        on-profile: linux
    mongodb:
      embedded:
        version: 5.0.0
  ```

yml은 위와 같이 구성했고, 커맨드로 아래와 같이 입력했을 때...

```bash
mvnw clean spring-boot:run -Dspring.profiles.active=linux
```

윈도우 환경에서는 linux 프로파일로 선택이 잘 되었는데, Ubuntu나 Rocky에서는 항상 default 프로파일로 잡힌다. 😥

프로필이 왜 안먹는지 이부분도 확인중...
